version: '3.8'

services:
  web:
    build: .
    command: python src/python/web_app/app.py
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/bond_valuation
      - FLASK_ENV=development

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=bond_valuation
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

volumes:
  postgres_data:
