name: bond-valuation
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - numpy
    - scipy
    - pandas
    - plotly
    - matplotlib
    - requests
    - flask
    - reportlab
    - tensorflow
    - vaderSentiment
    - openpyxl
    - pybind11
    - pytest
    - pytest-cov
    - flake8
    - black
